# Commit all of the i18n changes
# Requires a ~/.netrc-api file present with valid credentials

# Assume we're running in the zap-mgmt-scripts directory
cd ..

# zaproxy
cd zaproxy
git add src
git commit -m "Latest files from Crowdin"
git push origin
curl --data '{ "title": "Latest files from Crowdin",  "body": "Autogenerated PR from zapbot",  "head": "zapbot:develop",  "base": "develop" }' --netrc-file ~/.netrc-api https://api.github.com/repos/zaproxy/zaproxy/pulls
cd ..

# zap-extensions
cd zap-extensions
git add src
git commit -m "Latest files from Crowdin"
git push origin
curl --data '{ "title": "Latest files from Crowdin",  "body": "Autogenerated PR from zapbot",  "head": "zapbot:master",  "base": "master" }' --netrc-file ~/.netrc-api https://api.github.com/repos/zaproxy/zap-extensions/pulls
cd ..

# zap-extensions beta
cd zap-extensions_beta
git add src
git commit -m "Latest files from Crowdin"
git push origin
curl --data '{ "title": "Latest files from Crowdin",  "body": "Autogenerated PR from zapbot",  "head": "zapbot:beta",  "base": "beta" }' --netrc-file ~/.netrc-api https://api.github.com/repos/zaproxy/zap-extensions/pulls
cd ..

# zap-extensions alpha
cd zap-extensions_alpha
git add src
git commit -m "Latest files from Crowdin"
git push origin
curl --data '{ "title": "Latest files from Crowdin",  "body": "Autogenerated PR from zapbot",  "head": "zapbot:alpha",  "base": "alpha" }' --netrc-file ~/.netrc-api https://api.github.com/repos/zaproxy/zap-extensions/pulls
cd ..
