#!/usr/bin/env bash

cd ../zap-extensions

ant -f build/build.xml

java -cp build/build org.zaproxy.zap.extension.quickstart.launch.GenerateQuickStartLangFile > ../zap-admin/files/launch/2.7.html
ls -l ../zap-admin/files/launch/2.7.html

cd ../zap-admin
git add files/launch/2.7.html
git commit -m "Latest translation from Crowdin"
git push origin
curl --data '{ "title": "Latest translation from Crowdin",  "body": "Autogenerated PR from zapbot",  "head": "zapbot:master",  "base": "master" }' --netrc-file ~/.netrc-api https://api.github.com/repos/zaproxy/zap-admin/pulls
