env:
  contexts:
  - name: Authentication Test
    urls:
    - http://testfire.net
    includePaths:
    - https?://testfire.net.*
    authentication:
      method: browser
      parameters:
        loginPageUrl: http://testfire.net/login.jsp
        loginPageWait: 2
        browserId: firefox-headless
        steps:
        - description: Fill Username
          type: USERNAME
          cssSelector: "#uid"
          value: jsmith
          timeout: 1000
      verification:
        method: poll
        loggedInRegex: \QCongratulations!\E
        loggedOutRegex: \Q 403 Forbidden\E
        pollFrequency: 60
        pollUnits: seconds
        pollUrl: http://testfire.net/bank/main.jsp
        pollPostData: ""
    sessionManagement:
      method: headers
      parameters:
        Cookie: "JSESSIONID={%cookie:JSESSIONID%};"
    users:
    - name: jsmith
      credentials:
        password: demo1234
        username: jsmith
jobs:
- type: requestor
  parameters:
    user: jsmith
  requests:
  - name: Get Account Details
    url: 'http://testfire.net/bank/showAccount?listAccounts=800002'
    method: GET
    responseCode: 200

