env:
  contexts:
  - name: Authentication Test
    urls:
    - http://testphp.vulnweb.com
    includePaths:
    - http://testphp.vulnweb.com.*
    authentication:
      method: browser
      parameters:
        loginPageUrl: http://testphp.vulnweb.com/login.php
        loginPageWait: 2
        browserId: firefox-headless
      verification:
        method: autodetect
    sessionManagement:
      method: autodetect
    users:
    - name: testuser
      credentials:
        password: ${testphp_pass}
        username: ${testphp_user}
jobs:
- type: requestor
  parameters:
    user: testuser
  requests:
  - name: Get Account Details
    url: 'http://testphp.vulnweb.com/userinfo.php'
    method: GET
    responseCode: 200

