var DIR = "/zap/wrk/";
var NAME = "DOM XSS";
var TARGET = "dom";
var RULES = [40012, 40026, 200002, 200007, 210000, 210001, 210007, 210017, 210018, 220000, 220002, 220003, 220005, 220008, 220009];
var MIN_LEVEL = 2;
var INCLUDE_PATHS = [
	'/dompropagation/',
	'/eventtriggering/document/formSubmission/documentWrite',
	'/eventtriggering/document/formSubmission/eval',
	'/eventtriggering/document/formSubmission/innerHtml',
	'/eventtriggering/document/inputTyping/documentWrite',
	'/eventtriggering/document/inputTyping/eval',
	'/eventtriggering/document/inputTyping/innerHtml',
	'/toxicdom/document/cookie/eval',
	'/toxicdom/document/cookie_set/documentWrite',
	'/toxicdom/document/cookie_set/eval',
	'/toxicdom/document/cookie_set/innerHtml',
	'/toxicdom/document/referrer/documentWrite',
	'/toxicdom/document/referrer/eval',
	'/toxicdom/document/referrer/innerHtml',
	'/toxicdom/external/localStorage/array/eval',
	'/toxicdom/external/localStorage/function/documentWrite',
	'/toxicdom/external/localStorage/function/eval',
	'/toxicdom/external/localStorage/function/innerHtml',
	'/toxicdom/external/localStorage/property/documentWrite',
	'/toxicdom/external/sessionStorage/array/eval',
	'/toxicdom/external/sessionStorage/function/documentWrite',
	'/toxicdom/external/sessionStorage/function/eval',
	'/toxicdom/external/sessionStorage/function/innerHtml',
	'/toxicdom/external/sessionStorage/property/documentWrite',
	'/toxicdom/localStorage/array/eval',
	'/toxicdom/localStorage/function/documentWrite',
	'/toxicdom/localStorage/function/eval',
	'/toxicdom/localStorage/function/innerHtml',
	'/toxicdom/localStorage/property/documentWrite',
	'/toxicdom/postMessage/complexMessageDocumentWriteEval',
	'/toxicdom/postMessage/documentWrite',
	'/toxicdom/postMessage/eval',
	'/toxicdom/postMessage/improperOriginValidationWithPartialStringComparison',
	'/toxicdom/postMessage/improperOriginValidationWithRegExp',
	'/toxicdom/postMessage/innerHtml',
	'/toxicdom/sessionStorage/array/eval',
	'/toxicdom/sessionStorage/function/documentWrite',
	'/toxicdom/sessionStorage/function/eval',
	'/toxicdom/sessionStorage/function/innerHtml',
	'/toxicdom/sessionStorage/property/documentWrite',
	'/toxicdom/window/name/documentWrite',
	'/toxicdom/window/name/eval',
	'/toxicdom/window/name/innerHtml',
	'/toxicdomscripts/localStorage/array/eval',
	'/toxicdomscripts/localStorage/function/documentWrite',
	'/toxicdomscripts/localStorage/function/eval',
	'/toxicdomscripts/localStorage/function/innerHtml',
	'/toxicdomscripts/localStorage/property/documentWrite',
	'/toxicdomscripts/sessionStorage/array/eval',
	'/toxicdomscripts/sessionStorage/function/documentWrite',
	'/toxicdomscripts/sessionStorage/function/eval',
	'/toxicdomscripts/sessionStorage/function/innerHtml',
	'/toxicdomscripts/sessionStorage/property/documentWrite',
];
var BROKEN_PATHS = [];
