name: ZAP vs Wavsep

on: 
  schedule:
    # 4:30 every day
    - cron:  '40 3 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Clone zap-mgmt-scripts
      run: |
        export GITHUB_USER=zapbot
        git config --global user.email "12745184+zapbot@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        git clone https://github.com/$GITHUB_USER/zap-mgmt-scripts.git

    - name: Scan Wavsep
      run: |
        # start Wavsep
        docker run --rm -p 8080:8080 -p 3306:3306 zaproxy/wavsep &
        sleep 20

        cd zap-mgmt-scripts/scans/wavsep
        # Need to do this so the zap user in docker can write to the directory
        mkdir res
        chmod a+w res
        docker run -v $(pwd):/zap/wrk/:rw --network host ghcr.io/zaproxy/zaproxy:nightly zap.sh -cmd -port 9090 -silent -autorun /zap/wrk/wavsep.yaml

    - name: Upload results to S3
      continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWSCLI_SSP_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSCLI_SSP_SECRET }}
        AWS_DEFAULT_REGION: us-east-2
      run: |
        pip install pyyaml
        DATE=$(date +%Y-%m-%d)
        python3 zap-mgmt-scripts/scans/yaml_to_jsonl.py $DATE wavsep \
          zap-mgmt-scripts/scans/wavsep/res/*.yml \
          | aws s3 cp - s3://ssp-project-zap/scans/raw/wavsep/$DATE.jsonl

