name: ZAP vs Webseclab

on: 
  schedule:
    - cron:  '0 4 * * *' # 4 am every day
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Clone zap-mgmt-scripts and zaproxy-website
      run: |
        # Setup git details
        export GITHUB_USER=zapbot
        export GITHUB_TOKEN=${{ secrets.ZAPBOT_TOKEN }}
        git config --global user.email "12745184+zapbot@users.noreply.github.com"
        git config --global user.name $GITHUB_USER
        git clone https://github.com/$GITHUB_USER/zap-mgmt-scripts.git

        git clone https://github.com/$GITHUB_USER/zaproxy-website.git

    - name: Start Webseclab
      run: |
        docker run --network="host" -p 9090:9090 -d psiinon/webseclab

    - name: Scan Webseclab
      run: |
        cd zap-mgmt-scripts/scans/webseclab
        # Need to do this so the zap user in docker can write to the file
        touch reflected.yml
        chmod a+w reflected.yml
        docker run -v $(pwd):/zap/wrk/:rw --network="host" -t ghcr.io/zaproxy/zaproxy:nightly zap.sh -cmd -silent -autorun /zap/wrk/webseclab.yaml -config "scanner.injectable=11" -config "scanner.scanHeadersAllRequests=true"
        cp reflected.yml ../../../zaproxy-website/site/data/scans/webseclab/

    - name: Raise a PR on the website
      run: |
        cd zaproxy-website

        git checkout -b webseclab

        # Update the index to be sure git is aware of changes
        git update-index -q --refresh
        ## If there are changes: comment, commit, PR
        if ! git diff-index --quiet HEAD --; then
          gh repo set-default zaproxy/zaproxy-website
          git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/zaproxy-website.git
          git add site/data/scans/webseclab/*
          git commit -sm "Updated Webseclab Results"
          git push -u origin $BRANCH -f
          gh pr view --json mergedAt|jq -e '.mergedAt' && gh pr create --fill
        fi
